# Generated by Django 6.0.2 on 2026-02-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('request_id', models.CharField(blank=True, default='', max_length=64, verbose_name='Request ID')),
                ('action', models.CharField(max_length=200, verbose_name='Действие')),
                ('object_type', models.CharField(blank=True, default='', max_length=100, verbose_name='Тип объекта')),
                ('object_id', models.CharField(blank=True, default='', max_length=100, verbose_name='ID объекта')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Данные')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
            ],
            options={
                'verbose_name': 'Событие аудита',
                'verbose_name_plural': 'События аудита',
                'db_table': 'audit_events',
            },
        ),
    ]
