# Generated by Django 6.0.2 on 2026-02-07 20:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Дата создания пользователя в legacy системе (переносим как есть).', verbose_name='Создан'),
        ),
    ]
