graph LR
  endUser["Конечный<br/>пользователь"] --> createTicket["Создание<br/>заявки"]
  endUser --> viewOwn["Просмотр своих<br/>заявок"]
  endUser --> viewOwnAssets["Просмотр своей<br/>техники"]

  operator["Оператор"] --> processTicket["Обработка и<br/>маршрутизация заявки"]
  operator --> assignExec["Назначение<br/>исполнителя"]
  operator --> viewUserAssets["Просмотр техники<br/>пользователя"]

  executor["Исполнитель"] --> performWork["Исполнение<br/>заявки"]
  executor --> updateStatus["Изменение статуса<br/>в рамках полномочий"]

  admin["Администратор"] --> manageUsers["Управление<br/>пользователями и ролями"]
  admin --> manageAssets["Ведение карточек<br/>активов"]
  admin --> auditReview["Просмотр журнала<br/>аудита"]
