stateDiagram-v2
  [*] --> NewTask
  NewTask: Новая
  InWork: В работе
  DoneTask: Выполнена
  ClosedTask: Закрыта
  NewTask --> InWork: назначение исполнителя
  InWork --> DoneTask: выполнение работ
  DoneTask --> ClosedTask: подтверждение результата
  InWork --> NewTask: переоткрытие
