erDiagram
  ЗАЯВКА ||--o{ ВЛОЖЕНИЕ : "имеет"
  ПОЛЬЗОВАТЕЛЬ ||--o{ АКТИВ : "ответственный"
  ЛОКАЦИЯ ||--o{ АКТИВ : "размещён в"
  ПОЛЬЗОВАТЕЛЬ ||--o{ ЗАЯВКА : "автор"
  ПОЛЬЗОВАТЕЛЬ ||--o| ЗАЯВКА : "исполнитель"
  ЗАЯВКА }o--o{ АКТИВ : "связана с"
  АКТИВ {
    int id
    string инв_номер
    string тип
  }
  ЗАЯВКА {
    int id
    string описание
    string статус
  }
  ПОЛЬЗОВАТЕЛЬ {
    int id
    string ФИО
  }
  ЛОКАЦИЯ {
    int id
    string подразделение
  }
  ВЛОЖЕНИЕ {
    int id
    string имя_файла
  }
