graph LR
  c0["Control<br/>Регламенты учёта и обработки заявок<br/>Роли доступа и политика безопасности<br/>Требования к аудиту и отчётности"]
  i0["Input<br/>Сведения о технических средствах<br/>Обращения пользователей<br/>Данные о пользователях и локациях"]
  a0["A-0<br/>Управление учётом<br/>технических средств<br/>и обработкой заявок"]
  o0["Output<br/>Актуальные карточки активов<br/>Зарегистрированные и обработанные заявки<br/>Отчёты, выборки и журнал аудита"]
  m0["Mechanism<br/>Пользователи, операторы, администратор<br/>Прототип ИАС<br/>База данных и файловое хранилище"]

  c0 -->|"C"| a0
  i0 -->|"I"| a0
  a0 -->|"O"| o0
  m0 -->|"M"| a0
