# Generated by Django 6.0.2 on 2026-02-07 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareInstall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_id', models.IntegerField(help_text='На Фазе 3 держим как int. На Фазе 5+ переведём на FK к assets.Equipment.', verbose_name='ID оборудования')),
                ('installed_at', models.DateTimeField(auto_now_add=True, verbose_name='Установлено')),
                ('version', models.CharField(blank=True, max_length=100, verbose_name='Версия')),
            ],
            options={
                'verbose_name': 'Установка ПО',
                'verbose_name_plural': 'Установки ПО',
                'db_table': 'software_installs',
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('vendor', models.CharField(blank=True, max_length=255, verbose_name='Производитель')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'ПО',
                'verbose_name_plural': 'ПО',
                'db_table': 'software',
                'indexes': [models.Index(fields=['name'], name='software_name_6ec316_idx'), models.Index(fields=['vendor'], name='software_vendor_10fed7_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'vendor'), name='uq_sw_name_vendor')],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, verbose_name='Лицензионный ключ')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Действует с')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Действует до')),
                ('seats', models.PositiveIntegerField(default=1, verbose_name='Кол-во мест')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='software.software', verbose_name='ПО')),
            ],
            options={
                'verbose_name': 'Лицензия',
                'verbose_name_plural': 'Лицензии',
                'db_table': 'licenses',
            },
        ),
    ]
