# Generated by Django 6.0.2 on 2026-02-07 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('software', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareinstall',
            name='installed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_installs', to=settings.AUTH_USER_MODEL, verbose_name='Кто установил'),
        ),
        migrations.AddField(
            model_name='softwareinstall',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installs', to='software.license', verbose_name='Лицензия'),
        ),
        migrations.AddField(
            model_name='softwareinstall',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installs', to='software.software', verbose_name='ПО'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['software'], name='licenses_softwar_0f978c_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['valid_to'], name='licenses_valid_t_758d21_idx'),
        ),
        migrations.AddIndex(
            model_name='softwareinstall',
            index=models.Index(fields=['equipment_id'], name='software_in_equipme_1e823e_idx'),
        ),
        migrations.AddIndex(
            model_name='softwareinstall',
            index=models.Index(fields=['software'], name='software_in_softwar_892b8d_idx'),
        ),
        migrations.AddIndex(
            model_name='softwareinstall',
            index=models.Index(fields=['installed_at'], name='software_in_install_946bf9_idx'),
        ),
    ]
