# Generated by Django 6.0.2 on 2026-02-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(max_length=50, verbose_name='Тип изменения')),
                ('old_value', models.TextField(blank=True, verbose_name='Старое значение')),
                ('new_value', models.TextField(blank=True, verbose_name='Новое значение')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'История оборудования',
                'verbose_name_plural': 'История оборудования',
                'db_table': 'equip_history',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'db_table': 'equipment',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('location_type', models.CharField(choices=[('кабинет', 'кабинет'), ('склад', 'склад'), ('серверная', 'серверная'), ('лаборатория', 'лаборатория'), ('другое', 'другое')], max_length=50, verbose_name='Тип')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='PartCharValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Значение характеристики',
                'verbose_name_plural': 'Значения характеристик',
                'db_table': 'part_char_values',
            },
        ),
        migrations.CreateModel(
            name='SprChar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Характеристика')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('measurement_unit', models.CharField(blank=True, max_length=100, verbose_name='Ед. изм.')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
                'db_table': 'spr_chars',
            },
        ),
        migrations.CreateModel(
            name='SprPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Комплектующая',
                'verbose_name_plural': 'Комплектующие',
                'db_table': 'spr_parts',
            },
        ),
    ]
