# Generated by Django 6.0.2 on 2026-02-07 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equiphistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_changes', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to=settings.AUTH_USER_MODEL, verbose_name='Закреплено за пользователем'),
        ),
        migrations.AddField(
            model_name='equiphistory',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='assets.equipment', verbose_name='Оборудование'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['location_type'], name='locations_locatio_f7b031_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['floor'], name='locations_floor_02c0eb_idx'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='assets.location', verbose_name='Локация'),
        ),
        migrations.AddField(
            model_name='partcharvalue',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_char_values', to='assets.equipment', verbose_name='Оборудование'),
        ),
        migrations.AddField(
            model_name='partcharvalue',
            name='char',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_values', to='assets.sprchar', verbose_name='Характеристика'),
        ),
        migrations.AddField(
            model_name='partcharvalue',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='char_values', to='assets.sprpart', verbose_name='Комплектующая'),
        ),
        migrations.AddIndex(
            model_name='equiphistory',
            index=models.Index(fields=['equipment'], name='equip_histo_equipme_494161_idx'),
        ),
        migrations.AddIndex(
            model_name='equiphistory',
            index=models.Index(fields=['changed_by'], name='equip_histo_changed_a36ba9_idx'),
        ),
        migrations.AddIndex(
            model_name='equiphistory',
            index=models.Index(fields=['change_date'], name='equip_histo_change__874d0e_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['user'], name='equipment_user_id_99eefc_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['location'], name='equipment_locatio_7c627d_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['created_at'], name='equipment_created_d183c3_idx'),
        ),
        migrations.AddIndex(
            model_name='partcharvalue',
            index=models.Index(fields=['equipment'], name='part_char_v_equipme_6f432e_idx'),
        ),
        migrations.AddIndex(
            model_name='partcharvalue',
            index=models.Index(fields=['part'], name='part_char_v_part_id_3c3fde_idx'),
        ),
        migrations.AddIndex(
            model_name='partcharvalue',
            index=models.Index(fields=['char'], name='part_char_v_char_id_115ae8_idx'),
        ),
        migrations.AddConstraint(
            model_name='partcharvalue',
            constraint=models.UniqueConstraint(fields=('equipment', 'part', 'char'), name='uq_part_char_value'),
        ),
    ]
