# Generated by Django 6.0.2 on 2026-02-07 20:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Дата создания вложения в legacy системе (переносим как есть).', verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Дата создания заявки в legacy системе (переносим как есть).', verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Дата последнего обновления заявки в legacy системе (переносим как есть).', verbose_name='Обновлена'),
        ),
    ]
